Document: zipnish-ui
Title: Debian zipnish-ui Manual
Author: <insert document author here>
Abstract: This manual describes what zipnish-ui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zipnish-ui/zipnish-ui.sgml.gz

Format: postscript
Files: /usr/share/doc/zipnish-ui/zipnish-ui.ps.gz

Format: text
Files: /usr/share/doc/zipnish-ui/zipnish-ui.text.gz

Format: HTML
Index: /usr/share/doc/zipnish-ui/html/index.html
Files: /usr/share/doc/zipnish-ui/html/*.html
