Vagrant.configure(2) do |config|

	# jenkins
	config.vm.define 'jenkins' do |jenkins|
		jenkins.vm.box = "ubuntu/precise64"
		jenkins.vm.network :private_network, ip: "192.168.38.15"
		jenkins.vm.provision :shell, path: "provisioning/jenkins.sh"
	end

	# el6
	config.vm.define 'el6' do |jenkins|
		jenkins.vm.box = "geerlingguy/centos6"
		jenkins.vm.network :private_network, ip: "192.168.38.25"
	end
end
