Vagrant.configure(2) do |config|
	config.ssh.insert_key = false
	config.vm.box = 'ubuntu/vivid64'

	# user interface
	config.vm.define 'ui' do |ui|
		ui.vm.hostname = 'ui'
		ui.vm.network :private_network, ip: '192.168.75.11'
	end

	# database
	config.vm.define 'db' do |db|
		db.vm.hostname = 'db'
		db.vm.network :private_network, ip: '192.168.75.12'
	end

	# varnish cache, log reader
	config.vm.define 'backend' do |backend|
		backend.vm.hostname = 'backend'
		backend.vm.network :private_network, ip: '192.168.75.13'
	end

	# example application
	config.vm.define 'exampleapp' do |exampleapp|
		exampleapp.vm.hostname = 'exampleapp'
		exampleapp.vm.network :private_network, ip: '192.168.75.14'
	end
end
